resolver: lts-16.13
# allow-never: true

compiler: ghc-8.11.0.20200527

packages:
  - '.'

extra-deps:
  - primitive-0.7.1.0

system-ghc: true
extra-path:
  - /home/andorp/part1/Source/ghc-whole-program-compiler-project/ghc-wpc/_build/stage1/bin
